/*
 This program senses walls, and stops the robot if it gets too close.
 For straight ahead, it detects the obstruction with a sensor that we attached to the front of the robot.
 For when the robot's corners hit a wall, the robot detects the wall using click sensors on either side.
 */
//configuring button, switches, motors, and sensors
#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Sensor, dgtl3,  input,          sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  leftswitch,     sensorTouch)
#pragma config(Sensor, dgtl9,  rightswitch,    sensorTouch)
#pragma config(Motor,  port1,           rightmotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	//click the button to initialize the process
	while( SensorValue(button) == 0 ){
		motor[leftmotor] = 0;
		motor[rightmotor] = 0;
	}

	//move forwards until either of the switches are pushed (hit the wall) or sonar sensor is close to the wall
	//sonar sensor will sense straight ahead, switches for when it makes contact on the front corners of the robot
	while( SensorValue(input)>25 && SensorValue(leftswitch)==0 && SensorValue(rightswitch)==0 ){
		motor[leftmotor] = 50;
		motor[rightmotor] = 50;
	}

	//once we exit the previous loop, then it means we are in close proximity to a wall. So we stop the robot
	motor[leftmotor] = 0;
	motor[rightmotor] = 0;
}
